Repository unicef/sir-poc-fe, pull requests merged in 2018-10, with the labels that each got.

#202 Adds toggle button for showing/hiding filters on list pages
  src/components/events-module/events-list.js
  src/components/incidents-module/incidents-list.js
  src/components/styles/filters-styles.js
Labels: ready

#188 Incidents timeline
  polymer.json
  src/actions/app.js
  src/actions/incidents.js
  src/components/common/errors-box.js
  src/components/history-components/history-helpers.js
  src/components/history-components/revisions-list.js
  src/components/incidents-module/add-comment.js
  src/components/incidents-module/display-comment.js
  src/components/incidents-module/history/incident-history-controller.js
  src/components/incidents-module/history/incident-timeline.js
  src/components/incidents-module/incident-comments.js
  src/components/incidents-module/incident-review.js
  src/components/incidents-module/incidents-base-view.js
  src/components/incidents-module/incidents-controller.js
  src/components/incidents-module/view-incident.js
  src/components/styles/app-theme.js
  src/components/styles/shared-styles.js
  src/config/endpoints.js
Labels: ready

#204 Update sorting on events and incidents lists
  src/components/events-module/events-list.js
  src/components/incidents-module/incidents-list.js
Labels: ready

#192 Feature add review fields
  src/components/events-module/events-base-view.js
  src/components/incidents-module/impact/forms/evacuation.js
  src/components/incidents-module/impact/forms/non-un-personnel.js
  src/components/incidents-module/impact/forms/premise.js
  src/components/incidents-module/impact/forms/programme.js
  src/components/incidents-module/impact/forms/property.js
  src/components/incidents-module/impact/forms/un-personnel.js
  src/components/incidents-module/incidents-base-view.js
Labels: ready

#206 Removes primary person fields from incident base view
  src/components/dashboard-module/dashboard-list.js
  src/components/incidents-module/incidents-base-view.js
  src/components/incidents-module/incidents-list.js
  src/models/incident-model.js
Labels: ready

#210 Fixes export for filtered country
  src/components/incidents-module/incidents-list.js
Labels: help wanted

#186 Jwt token
  index.html
  package-lock.json
  src/actions/app.js
  src/components/app-shell.js
  src/components/auth/jwt/msal-authentication.js
  src/components/auth/sir-login.js
  src/components/common/list-common-mixin.js
  src/components/common/navigation-helper.js
  src/components/common/request-helper.js
  src/components/dashboard-module/dashboard-controller.js
  src/components/dashboard-module/dashboard-list.js
  src/components/events-module/events-list.js
  src/components/history-components/revisions-list.js
  src/components/incidents-module/incidents-list.js
  src/components/incidents-module/view-incident.js
  src/components/styles/app-theme.js
  src/components/styles/button-styles.js
  src/components/styles/shared-styles.js
Labels: ready

#211 Updates to review fields
  src/components/common/review-fields.js
  src/components/events-module/add-event.js
  src/components/events-module/events-base-view.js
  src/components/incidents-module/add-incident.js
  src/components/incidents-module/impact/forms/evacuation.js
  src/components/incidents-module/impact/forms/non-un-personnel.js
  src/components/incidents-module/impact/forms/premise.js
  src/components/incidents-module/impact/forms/programme.js
  src/components/incidents-module/impact/forms/property.js
  src/components/incidents-module/impact/forms/un-personnel.js
  src/components/incidents-module/incidents-base-view.js
Labels: ready, review

#213 Auto complete user- populate all fields
  src/components/incidents-module/impact/forms/non-un-personnel.js
  src/components/incidents-module/impact/forms/un-personnel.js
Labels: ready, review

#214 Fix incident error
  src/actions/incidents.js
Labels: ready, review

#215 Updates creation_date field to created_on
  src/components/dashboard-module/dashboard-list.js
Labels: ready, review

#212 Feature incidents buttons
  package-lock.json
  src/components/incidents-module/add-incident.js
  src/components/incidents-module/impact/forms/evacuation.js
  src/components/incidents-module/impact/forms/impact-form-base.js
  src/components/incidents-module/impact/forms/non-un-personnel.js
  src/components/incidents-module/impact/forms/premise.js
  src/components/incidents-module/impact/forms/programme.js
  src/components/incidents-module/impact/forms/property.js
  src/components/incidents-module/impact/forms/un-personnel.js
  src/components/incidents-module/incidents-base-view.js
  src/components/incidents-module/view-incident.js
  src/components/styles/app-theme.js
  src/components/styles/button-styles.js
  src/components/styles/shared-styles.js
Labels: in progress

#216 Changes authority value in Msal.UserAgentApplication
  src/components/auth/jwt/msal-authentication.js
Labels: ready

#221 Added caching exception for /admin/ routes
  sw-precache-config.js
Labels: ready

#219 Fix incident tabs
  src/components/common/etools-tabs.js
Labels: ready

#222 added routing exceptions for file uploads and exports
  sw-precache-config.js
Labels: ready, review

#223 fix incidents export request auth
  .eslintrc.json
  src/actions/app.js
  src/actions/incidents.js
  src/components/auth/jwt/msal-authentication.js
  src/components/auth/sir-login.js
  src/components/common/request-helper.js
  src/components/common/review-fields.js
  src/components/dashboard-module/dashboard-controller.js
  src/components/dashboard-module/dashboard-list.js
  src/components/events-module/events-base-view.js
  src/components/incidents-module/history/incident-timeline.js
  src/components/incidents-module/impact/forms/evacuation.js
  src/components/incidents-module/impact/forms/impact-form-base.js
  src/components/incidents-module/impact/forms/non-un-personnel.js
  src/components/incidents-module/impact/forms/premise.js
  src/components/incidents-module/impact/forms/programme.js
  src/components/incidents-module/impact/forms/property.js
  src/components/incidents-module/impact/forms/un-personnel.js
  src/components/incidents-module/incidents-base-view.js
  src/components/incidents-module/incidents-list.js
  src/reducers/incidents.js
  sw-precache-config.js
Labels: ready, review

#224 Fix redirect aprove reject
  src/components/incidents-module/incident-review.js
Labels: ready

#226 request auth header updates
  src/components/auth/jwt/msal-authentication.js
Labels: ready

#225 On click related doc name - dw using jwt
  src/components/incidents-module/incidents-base-view.js
Labels: ready, review

#218 added data sanitization for latitude and longitude
  src/actions/incidents.js
  src/components/common/utils.js
Labels: ready

#228 Tokenize Related docs upload
  src/components/incidents-module/incidents-base-view.js
Labels: ready, review

#227 prevent edit for submitted incidents
  src/actions/incidents.js
  src/components/common/utils.js
  src/components/events-module/events-base-view.js
  src/components/incidents-module/add-incident.js
  src/components/incidents-module/edit-incident.js
  src/components/incidents-module/incident-review.js
  src/components/incidents-module/incidents-base-view.js
  src/components/incidents-module/incidents-list.js
  src/components/incidents-module/view-incident.js
Labels: ready

#230 prevent incident save request with no payload
  package-lock.json
  src/actions/incidents.js
Labels: ready

#235 Fix wrong redirect caused by timing issues
  src/components/incidents-module/edit-incident.js
  src/components/incidents-module/incidents-base-view.js
Labels: ready, review

#234 Fix lingering errors
  src/actions/incident-impacts.js
  src/actions/incidents.js
  src/components/app-shell.js
  src/components/events-module/events-base-view.js
  src/components/incidents-module/impact/forms/impact-form-base.js
  src/components/incidents-module/impact/forms/un-personnel.js
  src/components/incidents-module/impact/impacts-view.js
  src/components/incidents-module/incident-review.js
  src/components/incidents-module/incidents-base-view.js
Labels: ready, review

#232 Fix change city input
  src/components/history-components/diff-view.js
  src/components/incidents-module/impact/forms/evacuation.js
  src/components/incidents-module/impact/forms/non-un-personnel.js
  src/components/incidents-module/impact/forms/premise.js
  src/components/incidents-module/impact/forms/un-personnel.js
  src/components/incidents-module/incidents-base-view.js
  src/components/incidents-module/incidents-list.js
Labels: ready

#231 Fix circleCi issues
  .travis.yml
  package-lock.json
  wct.conf.json
Labels: ready, review

#236 Update auth
  src/components/auth/jwt/msal-authentication.js
Labels: ready

#242 Changes redirect on incident save
  src/components/incidents-module/add-incident.js
Labels: ready

#240 Specifies default denomination for property values in impacts
  src/components/incidents-module/impact/forms/property.js
  src/components/incidents-module/impact/lists/properties.js
Labels: ready, review

#237 Fix change dialogs
  package-lock.json
  package.json
  src/components/incidents-module/buttons/approve.js
  src/components/incidents-module/buttons/buttons-base.js
  src/components/incidents-module/buttons/reject.js
  src/components/incidents-module/buttons/submit.js
  src/components/incidents-module/incident-review.js
  src/components/incidents-module/incidents-base-view.js
  src/components/incidents-module/view-incident.js
Labels: review

#233 buttons style updates, css clean up
  src/components/incidents-module/edit-incident.js
  src/components/incidents-module/impact/impact-controller.js
  src/components/incidents-module/impact/impacts-view.js
  src/components/incidents-module/incidents-list.js
  src/components/styles/button-styles.js
Labels: ready

#217 Fix ios popup
  images/safari_share.png
  package.json
  src/components/app-shell.js
  src/components/snack-bar/ios-shortcut-dialog.js
Labels: in progress

#244 snackbar and ios install prompt now hidden on login page
  src/components/app-shell.js
Labels: ready, review
