Repository unicef/sir-poc-fe, pull requests merged in 2018-11, with the labels that each got.

#245 Refactor login page & fix install prompt on login
  index.html
  package-lock.json
  package.json
  polymer.json
  server.js
  src/actions/app.js
  src/components/app-loader.js
  src/components/app-shell.js
  src/components/auth/sir-login.js
  sw-precache-config.js
Labels: ready

#239 Changes label on non-un impact
  src/components/incidents-module/impact/forms/non-un-personnel.js
Labels: ready

#249 Changes welcome message
  src/components/auth/sir-login.js
Labels: ready

#248 Removes all but description from expanded row details on all lists
  src/components/dashboard-module/dashboard-list.js
  src/components/events-module/events-list.js
  src/components/incidents-module/incidents-list.js
Labels: ready

#250 Changes UN labels to UNICEF in impacts
  src/components/incidents-module/impact/forms/non-un-personnel.js
  src/components/incidents-module/impact/forms/premise.js
  src/components/incidents-module/impact/forms/programme.js
  src/components/incidents-module/impact/forms/property.js
  src/components/incidents-module/impact/forms/un-personnel.js
  src/components/incidents-module/impact/impacts-view.js
  src/components/incidents-module/impact/lists/non-un-personnel.js
  src/components/incidents-module/impact/lists/premises.js
  src/components/incidents-module/impact/lists/programmes.js
  src/components/incidents-module/impact/lists/un-personnel.js
Labels: ready

#246 Redux status now updates when status change action is successfull
  src/actions/incidents.js
  src/components/incidents-module/buttons/approve.js
Labels: ready

#254 Adds staff member question to enable autocomplete personnel
  src/components/incidents-module/impact/forms/un-personnel.js
Labels: ready

#253 Changes field order and adds message to attachments section
  src/components/incidents-module/incidents-base-view.js
Labels: ready

#251 Removes icon from time input
  src/components/incidents-module/incidents-base-view.js
Labels: ready

#252 Adds placeholder to city input on evacuations impact form
  src/components/incidents-module/impact/forms/evacuation.js
Labels: ready

#238 Contry options now filtered based on selected region
  src/components/common/utils.js
  src/components/incidents-module/impact/forms/evacuation.js
  src/components/incidents-module/impact/forms/impact-form-base.js
  src/components/incidents-module/impact/forms/non-un-personnel.js
  src/components/incidents-module/impact/forms/un-personnel.js
  src/components/incidents-module/incidents-base-view.js
Labels: ready, review

#261 User can now add related document on new incident form
  src/actions/incidents.js
  src/components/incidents-module/add-incident.js
  src/components/incidents-module/incidents-base-view.js
Labels: ready, review

#259 Makes some editorial changes (capitalization of labels etc)
  src/components/common/review-fields.js
  src/components/incidents-module/impact/forms/evacuation.js
  src/components/incidents-module/impact/forms/non-un-personnel.js
  src/components/incidents-module/impact/forms/premise.js
  src/components/incidents-module/impact/forms/programme.js
  src/components/incidents-module/impact/forms/property.js
  src/components/incidents-module/impact/forms/un-personnel.js
Labels: ready

#255 Button change
  src/components/incidents-module/add-incident.js
  src/components/incidents-module/edit-incident.js
  src/components/incidents-module/incidents-base-view.js
Labels: ready, review

#262 Branding changes
  images/favicon.ico
  images/manifest/icon-144x144.png
  images/manifest/icon-192x192.png
  images/manifest/icon-48x48.png
  images/manifest/icon-512x512.png
  images/manifest/icon-72x72.png
  images/manifest/icon-96x96.png
  images/unicef_logo.png
  images/unicef_logo_round.png
  index.html
  src/components/app-shell.js
  src/components/auth/sir-login.js
  src/components/styles/app-theme.js
Labels: ready

#260 Updates value for Address column on non-UNICEF impacts list
  src/components/incidents-module/impact/lists/non-un-personnel.js
Labels: ready

#263 Fixed issue with requests firing on login page
  src/components/app-loader.js
  src/components/auth/sir-login.js
Labels: ready

#264 Update confirmation dialogs for delete and reset
  src/actions/incidents.js
  src/components/incidents-module/add-incident.js
  src/components/incidents-module/buttons/delete.js
  src/components/incidents-module/buttons/reset.js
  src/components/incidents-module/edit-incident.js
  src/components/incidents-module/incident-review.js
Labels: ready

#209 Makes etools-tabs sticky on events/incidents views
  server.js
  src/components/app-shell.js
  src/components/events-module/events-controller.js
  src/components/incidents-module/incidents-controller.js
Labels: ready

#270 Fix app colors
  src/components/app-shell.js
  src/components/auth/sir-login.js
  src/components/common/etools-tabs.js
  src/components/events-module/events-controller.js
  src/components/incidents-module/incidents-controller.js
  src/components/styles/app-theme.js
Labels: ready

#265 Adds tooltips for impact types on persons, programmes, property
  src/components/incidents-module/impact/forms/impact-form-base.js
  src/components/incidents-module/impact/forms/non-un-personnel.js
  src/components/incidents-module/impact/forms/programme.js
  src/components/incidents-module/impact/forms/property.js
  src/components/incidents-module/impact/forms/un-personnel.js
Labels: ready

#267 Permissions system update
  src/actions/incidents.js
  src/actions/permissions-helpers.js
  src/components/app-shell.js
  src/components/common/permissions-base-class.js
  src/components/common/utils.js
  src/components/dashboard-module/dashboard-list.js
  src/components/events-module/add-event.js
  src/components/events-module/edit-event.js
  src/components/events-module/events-base-view.js
  src/components/events-module/events-list.js
  src/components/incidents-module/add-incident.js
  src/components/incidents-module/buttons/buttons-base.js
  src/components/incidents-module/buttons/reject.js
  src/components/incidents-module/edit-incident.js
  src/components/incidents-module/history/incident-history-controller.js
  src/components/incidents-module/history/incident-timeline.js
  src/components/incidents-module/impact/impacts-view.js
  src/components/incidents-module/impact/lists/evacuations.js
  src/components/incidents-module/impact/lists/non-un-personnel.js
  src/components/incidents-module/impact/lists/premises.js
  src/components/incidents-module/impact/lists/programmes.js
  src/components/incidents-module/impact/lists/properties.js
  src/components/incidents-module/impact/lists/un-personnel.js
  src/components/incidents-module/incident-review.js
  src/components/incidents-module/incidents-base-view.js
  src/components/incidents-module/incidents-list.js
  src/components/incidents-module/view-incident.js
  src/config/permissions.js
Labels: ready

#271 Update area input
  src/components/incidents-module/impact/forms/programme.js
Labels: ready

#272 Clear stored incident draft on logout
  src/actions/constants.js
  src/actions/incidents.js
  src/components/app-shell.js
  src/reducers/incidents.js
Labels: ready

#278 misc small timeline fixes
  src/components/incidents-module/history/incident-history-controller.js
  src/components/incidents-module/history/incident-timeline.js
Labels: ready

#274 Fixed cancel buttons for incidents
  src/components/events-module/events-base-view.js
  src/components/incidents-module/incidents-base-view.js
Labels: ready

#273 Disable user autocomplete while offline
  src/actions/app.js
  src/actions/static-data.js
  src/actions/users.js
  src/components/common/review-fields.js
  src/components/common/utils.js
  src/components/dashboard-module/dashboard-list.js
  src/components/history-components/revisions-list.js
  src/components/incidents-module/history/incident-timeline.js
  src/components/incidents-module/impact/forms/un-personnel.js
  src/components/incidents-module/impact/lists/evacuations.js
  src/components/incidents-module/impact/lists/non-un-personnel.js
  src/components/incidents-module/impact/lists/premises.js
  src/components/incidents-module/impact/lists/programmes.js
  src/components/incidents-module/impact/lists/properties.js
  src/components/incidents-module/impact/lists/un-personnel.js
  src/components/incidents-module/incident-review.js
  src/components/incidents-module/incidents-list.js
  src/reducers/users.js
  src/redux/store.js
Labels: ready

#277 Add validation messages
  src/components/events-module/add-event.js
  src/components/events-module/edit-event.js
  src/components/incidents-module/add-incident.js
  src/components/incidents-module/edit-incident.js
  src/components/incidents-module/impact/forms/evacuation.js
  src/components/incidents-module/impact/forms/non-un-personnel.js
  src/components/incidents-module/impact/forms/premise.js
  src/components/incidents-module/impact/forms/programme.js
  src/components/incidents-module/impact/forms/property.js
  src/components/incidents-module/impact/forms/un-personnel.js
Labels: ready

#275 Changes text warning and required fields for sexual assault on unicef and non-unicef impacts
  src/components/incidents-module/impact/forms/non-un-personnel.js
  src/components/incidents-module/impact/forms/un-personnel.js
Labels: ready

#276 refactor filters
  src/components/app-shell.js
  src/components/common/list-base-class.js
  src/components/common/list-common-mixin.js
  src/components/common/utils.js
  src/components/events-module/events-controller.js
  src/components/events-module/events-list.js
  src/components/incidents-module/buttons/review-eod.js
  src/components/incidents-module/incidents-controller.js
  src/components/incidents-module/incidents-list.js
Labels: ready

#279 Removed dashboard
  src/actions/app.js
  src/components/app-shell.js
  src/components/auth/jwt/msal-authentication.js
  src/components/dashboard-module/dashboard-controller.js
  src/components/dashboard-module/dashboard-list.js
Labels: ready

#280 New items count
  src/actions/incidents.js
  src/components/app-shell.js
  src/components/incidents-module/history/incident-history-controller.js
  src/components/incidents-module/history/incident-timeline.js
  src/components/incidents-module/incidents-list.js
  src/components/styles/app-theme.js
Labels: ready

#282 Adds staff wellbeing reviewer fields, button, and endpoint
  src/actions/incidents.js
  src/components/history-components/history-helpers.js
  src/components/incidents-module/buttons/review-wellbeing.js
  src/components/incidents-module/incident-review.js
  src/config/endpoints.js
  src/config/permissions.js
Labels: help wanted

#281 Fix plain auth on login
  server.js
  src/components/app-loader.js
  src/components/auth/sir-login.js
  src/redux/store.js
Labels: ready

#283 Fixed issue with data persisting on impact forms
  src/components/incidents-module/impact/forms/impact-form-base.js
Labels: ready

#284 Changed the way sign operations are shown in incident history
  src/components/incidents-module/history/incident-timeline.js
  src/components/incidents-module/incidents-base-view.js
Labels: ready
